### ISSUE TITLE
publishDist requires gnupg key

### ISSUE THREAD

**Issue by F21** [vlsi/vlsi-release-plugins#26]
I am testing out the gradle `publishDist` task for avatica.

```
# gradle publishDist -PasfTestSvnUsername=test -PasfTestSvnPassword=test -PasfTestNexusUsername=test -PasfTestNexusPassword=test -PasfTestGitSourceUsername=test -PasfTestGitSourcePassword=test -PallowUncommittedChanges -Prc=0            

> Configure project :
Building Apache Calcite Avatica 1.16.0

> Task :createReleaseTag
Created tag rel/avatica-1.16.0 -> Ref[refs/tags/rel/avatica-1.16.0=1d755dbfa86f23484d7f1744bca940d14ab4a0ab(-1)]

> Task :pushReleaseTag
Pushing tag to Git remote release-origin-test: git://127.0.0.1/calcite.git
Message from release-origin-test:
  refs/tags/rel/avatica-1.16.0: REJECTED_NONFASTFORWARD, dd0e8634c185cf92c41ea440e63e840590fca0dd -> 1d755dbfa86f23484d7f1744bca940d14ab4a0ab

> Task :release:signDistTar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':release:signDistTar'.
> Cannot perform signing task ':release:signDistTar' because it has no configured signatory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
11 actionable tasks: 5 executed, 6 up-to-date
```
It seems that `publishDist` requires the gpg key for signing. In particular it calls `:release:signDistTar`. Shouldn't the artifacts be signed already when running `prepareVote`? What is the purpose of the gpg key when running `publishDist`?

**Comment by vlsi** [comment]
Technically speaking the artifacts are used by the task to identify the names of the release files: https://github.com/vlsi/vlsi-release-plugins/blob/1fff89b7829adc43ccc8adc4f22e36b3e2ffaa31/plugins/stage-vote-release-plugin/src/main/kotlin/com/github/vlsi/gradle/release/StageVoteReleasePlugin.kt#L200-L201

Probably the logic could be updated to store the file names somewhere at the `prepareVote` time.

However, there's a catch: local `build` folder does not suit for that case because one can call `gradlew clean`, and the list of the files would be lost.

It looks like the way to go is to add a metadata file to https://dist.apache.org/repos/dist/dev/...or just assume that "everything within `/dev/release-candidate-folder`" could be moved to `/release` folder.

**Comment by F21** [comment]
Ah right, I see what it does now. Do you think it makes sense to just move the `/dev/rc` folder over to `/release`? That's what I've previously done for the docker script in avatica: https://github.com/apache/calcite-avatica/blob/master/docker.sh#L414

**Comment by vlsi** [comment]
That is non-trivial.

Apache JMeter stages all the files under https://dist.apache.org/repos/dist/dev/jmeter/apache-jmeter-5.2.1-rc1/ , and the release folders are split into `binaries` and `source`: https://dist.apache.org/repos/dist/release/jmeter/

On the good side, I've recently implemented a [wrapper](https://github.com/vlsi/vlsi-release-plugins/blob/1fff89b7829adc43ccc8adc4f22e36b3e2ffaa31/plugins/stage-vote-release-plugin/src/main/kotlin/com/github/vlsi/gradle/release/RemoveStaleArtifactsTask.kt#L71-L73) over `svn ls`, so it might indeed be a way to go (enumerate the files and move accordingly).
